using System;

namespace Learnify.Models
{
    public abstract class CourseItem
    {

        public enum ItemType
        {
            VIDEO,
            TEXT,
            TEST
        }
        private String Id { get; }
        private String CourseId { get; }
        public String Name { get; set; }
        public string Description { get; set; }
        public ItemType Type { get; set; }
        public string Length { get; set; }

        public CourseItem(String courseId, ItemType type)
        {
            this.Type = type;
            this.CourseId = courseId;
            Id = System.Guid.NewGuid().ToString();// should be generated by DB while new course is saved.
        }
    }
}