using System;

namespace Learnify.Models
{
    public abstract class CourseItem
    {

        public enum ItemType
        {
            VIDEO,
            TEXT,
            TEST
        }
        private String Id;
        public string Name { get; set; }
        public string Description { get; set; }
        public ItemType Type { get; set; }

        public CourseItem()
        {
            Id = System.Guid.NewGuid().ToString();// should be generated by DB while new course is saved.
        }
    }
}